### ISSUE TITLE
As a marketing analyst, I want a report showing all countries in the world, organized by population size, so that I can identify high-potential markets for expansion.

### ISSUE THREAD

**Issue by Ghost-Reaper** [brenda-leeCee/Devops-G3#31]

**Comment by larissaspascascio** [comment]
* Identify the relevant tables and columns in the world database.
* Write an SQL query to retrieve the population for all countries in the world.  Ensure the query pulls accurate country names and population data from the database.
* Modify the query to sort the countries by population in descending order.
* Validate and verify the results.

**Comment by larissaspascascio** [comment]
# Country Reports Completed

The implementation of country reports has been successfully completed. 🎉
