### ISSUE TITLE
As a marketing analyst, I want a report of all countries in a specific continent, organized by population size, so that I can tailor regional marketing campaigns

### ISSUE THREAD

**Issue by Ghost-Reaper** [brenda-leeCee/Devops-G3#32]

**Comment by larissaspascascio** [comment]
* Identify the relevant tables and columns in the world database.
 * Write an SQL query to retrieve the population of all countries within a specific continent.  Ensure the query filters by continent, includes the country name and population, and retrieves accurate data for the specified continent.
 * Validate and verify the results.

**Comment by larissaspascascio** [comment]
# Population Reports for All Countries in a Specific Continent Completed

The feature to generate population reports for all countries within a specific continent has been successfully completed. 🌍✅
