### ISSUE TITLE
As a marketing analyst, I want to generate a report of the top N populated countries in the world, to prioritize the top markets for international advertising

### ISSUE THREAD

**Issue by Ghost-Reaper** [brenda-leeCee/Devops-G3#33]

**Comment by larissaspascascio** [comment]
* Identify the relevant tables and columns in the world database. 
* Write an SQL query to retrieve the population of all countries in the world.  Ensure the query includes the country name and population.
* Modify the query to sort the countries by population in descending order and limit the result to the top N countries.
* Validate and verify the results

**Comment by larissaspascascio** [comment]
completed
