### ISSUE TITLE
As a marketing analyst, I want to see the top N populated countries in a continent, to determined resource allocation for campaigns

### ISSUE THREAD

**Issue by Ghost-Reaper** [brenda-leeCee/Devops-G3#34]
As a marketing analyst, I want to see the top N populated countries in a continent, to determined resource allocation for campaigns

**Comment by larissaspascascio** [comment]
* Identify the relevant tables and columns in the world database.
* Write an SQL query to retrieve the population of all countries within a specific continent.
* Make certain that the query filters for a given continent and retrieves the country name and its population.
* Validate and verify the results

**Comment by larissaspascascio** [comment]
# Report of a Country in a Continent Completed

The functionality to generate a report for a specific country within a continent has been successfully completed. ✅
