### ISSUE TITLE
As a marketing analyst, I want to generate a report of all cities in the world organized by population size, so that Supporting Retail and Distribution Decisions

### ISSUE THREAD

**Issue by Ghost-Reaper** [brenda-leeCee/Devops-G3#35]

**Comment by larissaspascascio** [comment]
* Identify the relevant tables and columns in the world database.
* Write an SQL query to retrieve the population for all cities worldwide.
* Modify the query to sort the cities by population in descending order.
* Validate and verify the results

**Comment by larissaspascascio** [comment]
completed
