### ISSUE TITLE
As a marketing analyst, I want to know the population of people living in cities versus those living in rural areas for each region so that I can decide on either urban-centric or rural-centric approach.

### ISSUE THREAD

**Issue by Ghost-Reaper** [brenda-leeCee/Devops-G3#38]

**Comment by larissaspascascio** [comment]
* Identify the relevant tables and columns from the world database.
* Write an SQL query to retrieve population data for both urban (cities) and rural areas across each region.
* Ensure the query distinguishes between urban and rural populations for each region and provides the total population for both categories.
* Analyze and verify the data.
