### ISSUE TITLE
As a marketing analyst, I want to know All the capital cities in the world organised by largest population to smallest to to consider global outreach.

### ISSUE THREAD

**Issue by Ghost-Reaper** [brenda-leeCee/Devops-G3#39]

**Comment by larissaspascascio** [comment]
* Identify the relevant tables and columns from the world database.
* Create and run the SQL query to get all capital cities, their population, and the country they belong to, organized by population in descending order
* Review and validate the results.

**Comment by larissaspascascio** [comment]
completed
